/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Verifica conectividad real con la base, no solo que el proceso viva (§9.5).
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description `request` lo exige slowapi para identificar la IP; no se lee nada mas de el.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/set-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Password */
        post: operations["set_password_api_v1_auth_set_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/request-password-setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Password Setup
         * @description Responde lo mismo exista o no el correo (§8.12). El evento sale del token del admin.
         */
        post: operations["request_password_setup_api_v1_auth_request_password_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exhibitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exhibitors */
        get: operations["list_exhibitors_api_v1_exhibitors_get"];
        put?: never;
        /** Create Exhibitor */
        post: operations["create_exhibitor_api_v1_exhibitors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exhibitors/{exhibitor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exhibitor */
        get: operations["get_exhibitor_api_v1_exhibitors__exhibitor_id__get"];
        put?: never;
        post?: never;
        /** Delete Exhibitor */
        delete: operations["delete_exhibitor_api_v1_exhibitors__exhibitor_id__delete"];
        options?: never;
        head?: never;
        /** Update Exhibitor */
        patch: operations["update_exhibitor_api_v1_exhibitors__exhibitor_id__patch"];
        trace?: never;
    };
    "/api/v1/me/exhibitor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Exhibitor */
        get: operations["my_exhibitor_api_v1_me_exhibitor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Quota
         * @description Cupo total vs. usado, desglosado por categoria. Calculado, nunca leido de una columna.
         */
        get: operations["my_quota_api_v1_me_quota_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Participants */
        get: operations["list_participants_api_v1_me_participants_get"];
        put?: never;
        /** Create Participant */
        post: operations["create_participant_api_v1_me_participants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/participants/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Participant */
        get: operations["get_participant_api_v1_me_participants__participant_id__get"];
        put?: never;
        post?: never;
        /** Delete Participant */
        delete: operations["delete_participant_api_v1_me_participants__participant_id__delete"];
        options?: never;
        head?: never;
        /** Update Participant */
        patch: operations["update_participant_api_v1_me_participants__participant_id__patch"];
        trace?: never;
    };
    "/api/v1/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Participants */
        get: operations["list_participants_api_v1_participants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Dashboard
         * @description Stands con credenciales asignadas vs. disponibles, agregado para toda la feria.
         */
        get: operations["admin_dashboard_api_v1_dashboard_admin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/exhibitors.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exhibitors Xlsx
         * @description Reporte accionable para el organizador: un stand por fila con su cupo real.
         */
        get: operations["exhibitors_xlsx_api_v1_reports_exhibitors_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/stand-sizes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stand Sizes */
        get: operations["stand_sizes_api_v1_rules_stand_sizes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Credentials */
        get: operations["credentials_api_v1_rules_credentials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminDashboard */
        AdminDashboard: {
            event: components["schemas"]["EventRead"];
            /** Exhibitors Total */
            exhibitors_total: number;
            /** Total M2 */
            total_m2: number;
            /** Participants Total */
            participants_total: number;
            /** Totals */
            totals: {
                [key: string]: components["schemas"]["CategoryTotals"];
            };
            /** Stand Categories */
            stand_categories: components["schemas"]["StandCategoryCount"][];
        };
        /** CategoryTotals */
        CategoryTotals: {
            /** Quota */
            quota: number;
            /** Assigned */
            assigned: number;
            /** Available */
            available: number;
        };
        /** ContactIn */
        ContactIn: {
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ContactRead */
        ContactRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
        };
        /** CredentialRuleRead */
        CredentialRuleRead: {
            /** Id */
            id: number;
            /** Category */
            category: string;
            /** Credentials Per Block */
            credentials_per_block: number;
            /** Block M2 */
            block_m2: number;
            /** Rounding Mode */
            rounding_mode: string;
        };
        /** EventRead */
        EventRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Year */
            year: number;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
        };
        /** ExhibitorCreate */
        ExhibitorCreate: {
            /** Tax Id */
            tax_id: string;
            /** Tax Id Type */
            tax_id_type: string;
            /** Legal Name */
            legal_name: string;
            /** Stand Name */
            stand_name: string;
            /** Address */
            address: string;
            /** Requested M2 */
            requested_m2: number;
            representative: components["schemas"]["RepresentativeIn"];
            /** Contacts */
            contacts: components["schemas"]["ContactIn"][];
        };
        /** ExhibitorDetail */
        ExhibitorDetail: {
            /** Id */
            id: number;
            /** Tax Id */
            tax_id: string;
            /** Tax Id Type */
            tax_id_type: string;
            /** Legal Name */
            legal_name: string;
            /** Stand Name */
            stand_name: string;
            /** Address */
            address: string;
            /** Requested M2 */
            requested_m2: number;
            /** Stand Category */
            stand_category: string;
            /** Quota */
            quota: {
                [key: string]: number;
            };
            /** Assigned */
            assigned: {
                [key: string]: number;
            };
            /** Available */
            available: {
                [key: string]: number;
            };
            representative: components["schemas"]["RepresentativeRead"];
            /** Contacts */
            contacts: components["schemas"]["ContactRead"][];
        };
        /**
         * ExhibitorRead
         * @description Fila de listado. `stand_category` y `quota` son DERIVADAS: no hay columna (§6.4, §6.7).
         */
        ExhibitorRead: {
            /** Id */
            id: number;
            /** Tax Id */
            tax_id: string;
            /** Tax Id Type */
            tax_id_type: string;
            /** Legal Name */
            legal_name: string;
            /** Stand Name */
            stand_name: string;
            /** Address */
            address: string;
            /** Requested M2 */
            requested_m2: number;
            /** Stand Category */
            stand_category: string;
            /** Quota */
            quota: {
                [key: string]: number;
            };
            /** Assigned */
            assigned: {
                [key: string]: number;
            };
            /** Available */
            available: {
                [key: string]: number;
            };
        };
        /**
         * ExhibitorUpdate
         * @description Todo opcional: es un PATCH. El representante y los contactos se editan aparte.
         */
        ExhibitorUpdate: {
            /** Legal Name */
            legal_name?: string | null;
            /** Stand Name */
            stand_name?: string | null;
            /** Address */
            address?: string | null;
            /** Requested M2 */
            requested_m2?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "representative";
            /** Event Id */
            event_id: number;
            /** Exhibitor Id */
            exhibitor_id: number | null;
        };
        /**
         * MyQuota
         * @description Cupo del stand propio, desglosado por categoria (§4).
         */
        MyQuota: {
            /** Exhibitor Id */
            exhibitor_id: number;
            /** Legal Name */
            legal_name: string;
            /** Stand Name */
            stand_name: string;
            /** Requested M2 */
            requested_m2: number;
            /** Stand Category */
            stand_category: string;
            /** Quota */
            quota: {
                [key: string]: number;
            };
            /** Assigned */
            assigned: {
                [key: string]: number;
            };
            /** Available */
            available: {
                [key: string]: number;
            };
            /** Participants Total */
            participants_total: number;
            /** Participants Without Email */
            participants_without_email: number;
        };
        /** Page[ExhibitorRead] */
        Page_ExhibitorRead_: {
            /** Items */
            items: components["schemas"]["ExhibitorRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[ParticipantRead] */
        Page_ParticipantRead_: {
            /** Items */
            items: components["schemas"]["ParticipantRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[ParticipantWithExhibitor] */
        Page_ParticipantWithExhibitor_: {
            /** Items */
            items: components["schemas"]["ParticipantWithExhibitor"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** ParticipantIn */
        ParticipantIn: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Identification */
            identification: string;
            /**
             * Identification Type
             * @enum {string}
             */
            identification_type: "CEDULA" | "RUC" | "PASSPORT" | "FOREIGN_ID";
            /** Phone */
            phone: string;
            /** Position */
            position: string;
            /**
             * Category
             * @enum {string}
             */
            category: "Exhibitor" | "Guest" | "Service";
            /** Provider Company */
            provider_company?: string | null;
            /** Email */
            email?: string | null;
        };
        /** ParticipantRead */
        ParticipantRead: {
            /** Id */
            id: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Identification */
            identification: string;
            /** Identification Type */
            identification_type: string;
            /** Phone */
            phone: string;
            /** Position */
            position: string;
            /** Category */
            category: string;
            /** Provider Company */
            provider_company: string | null;
            /** Email */
            email: string | null;
            /** Credential Notified At */
            credential_notified_at?: string | null;
        };
        /**
         * ParticipantUpdate
         * @description PATCH: el invariante de `provider_company` se revalida en el servicio sobre el
         *     resultado de la mezcla, porque aqui no se conoce la categoria que ya tiene la fila.
         */
        ParticipantUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Identification */
            identification?: string | null;
            /** Identification Type */
            identification_type?: ("CEDULA" | "RUC" | "PASSPORT" | "FOREIGN_ID") | null;
            /** Phone */
            phone?: string | null;
            /** Position */
            position?: string | null;
            /** Category */
            category?: ("Exhibitor" | "Guest" | "Service") | null;
            /** Provider Company */
            provider_company?: string | null;
            /** Email */
            email?: string | null;
        };
        /**
         * ParticipantWithExhibitor
         * @description Fila del listado global del admin: la misma credencial, mas de que stand es.
         */
        ParticipantWithExhibitor: {
            /** Id */
            id: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Identification */
            identification: string;
            /** Identification Type */
            identification_type: string;
            /** Phone */
            phone: string;
            /** Position */
            position: string;
            /** Category */
            category: string;
            /** Provider Company */
            provider_company: string | null;
            /** Email */
            email: string | null;
            /** Credential Notified At */
            credential_notified_at?: string | null;
            /** Exhibitor Id */
            exhibitor_id: number;
            /** Exhibitor Name */
            exhibitor_name: string;
        };
        /** PasswordSetupRequest */
        PasswordSetupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** RepresentativeIn */
        RepresentativeIn: {
            /** Full Name */
            full_name: string;
            /** Identification */
            identification: string;
            /** Identification Type */
            identification_type: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
            /** Position */
            position: string;
        };
        /** RepresentativeRead */
        RepresentativeRead: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /** Identification */
            identification: string;
            /** Identification Type */
            identification_type: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string;
            /** Position */
            position: string;
        };
        /** SetPasswordRequest */
        SetPasswordRequest: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /**
         * StandCategoryCount
         * @description Cuantos stands caen en cada rango. La categoria es informativa (§6.7).
         */
        StandCategoryCount: {
            /** Label */
            label: string;
            /** Min M2 */
            min_m2: number;
            /** Max M2 */
            max_m2: number;
            /** Exhibitors */
            exhibitors: number;
        };
        /** StandSizeRuleRead */
        StandSizeRuleRead: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Min M2 */
            min_m2: number;
            /** Max M2 */
            max_m2: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_password_api_v1_auth_set_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_password_setup_api_v1_auth_request_password_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordSetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_exhibitors_api_v1_exhibitors_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ExhibitorRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exhibitor_api_v1_exhibitors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExhibitorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExhibitorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exhibitor_api_v1_exhibitors__exhibitor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exhibitor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExhibitorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exhibitor_api_v1_exhibitors__exhibitor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exhibitor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exhibitor_api_v1_exhibitors__exhibitor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exhibitor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExhibitorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExhibitorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_exhibitor_api_v1_me_exhibitor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExhibitorDetail"];
                };
            };
        };
    };
    my_quota_api_v1_me_quota_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyQuota"];
                };
            };
        };
    };
    list_participants_api_v1_me_participants_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                category?: ("Exhibitor" | "Guest" | "Service") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ParticipantRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_participant_api_v1_me_participants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_participant_api_v1_me_participants__participant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_participant_api_v1_me_participants__participant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_participant_api_v1_me_participants__participant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_participants_api_v1_participants_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                exhibitor_id?: number | null;
                category?: ("Exhibitor" | "Guest" | "Service") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ParticipantWithExhibitor_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_dashboard_api_v1_dashboard_admin_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDashboard"];
                };
            };
        };
    };
    exhibitors_xlsx_api_v1_reports_exhibitors_xlsx_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Libro de Excel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": unknown;
                };
            };
        };
    };
    stand_sizes_api_v1_rules_stand_sizes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandSizeRuleRead"][];
                };
            };
        };
    };
    credentials_api_v1_rules_credentials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialRuleRead"][];
                };
            };
        };
    };
}
